"""
Hourly runner: checks memecoin signals, emails + logs to Notion on "buy now".

Required env vars (put in .env or export before running):
  NOTION_TOKEN      - Notion integration secret (starts with ntn_ or secret_)
  GMAIL_USER        - your Gmail address (sender)
  GMAIL_APP_PASS    - Gmail App Password (not your account password)

Optional:
  ALERT_EMAIL       - override recipient (default: vickomela36@gmail.com)
"""

import json
import os
import smtplib
import sys
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import requests

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
NOTION_TOKEN        = os.environ.get("NOTION_TOKEN", "")
NOTION_DATABASE_ID  = "951ef2fb-9adb-4524-bedb-ff2272b44560"
GMAIL_USER          = os.environ.get("GMAIL_USER", "")
GMAIL_APP_PASS      = os.environ.get("GMAIL_APP_PASS", "")
ALERT_EMAIL         = os.environ.get("ALERT_EMAIL", "vickomela36@gmail.com")

LOG_FILE = Path(__file__).parent / "signal_run.log"


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
def log(msg: str) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    line = f"[{ts}] {msg}"
    print(line, flush=True)
    with LOG_FILE.open("a") as f:
        f.write(line + "\n")


# ---------------------------------------------------------------------------
# Email via Gmail SMTP
# ---------------------------------------------------------------------------
def send_email(token: str, price: float, score: float, reason: str, timestamp: str) -> bool:
    if not GMAIL_USER or not GMAIL_APP_PASS:
        log("WARNING: GMAIL_USER or GMAIL_APP_PASS not set — skipping email")
        return False

    subject = f"Memecoin Buy Now Signal: {token}"
    body_html = f"""
<html><body>
<h2 style="color:#e63946;">Buy Now Signal Detected</h2>
<table style="border-collapse:collapse;font-family:monospace;">
  <tr><td><b>Token</b></td><td>{token}</td></tr>
  <tr><td><b>Price</b></td><td>${price}</td></tr>
  <tr><td><b>Score</b></td><td>{score} / 10</td></tr>
  <tr><td><b>Reason</b></td><td>{reason}</td></tr>
  <tr><td><b>Time</b></td><td>{timestamp}</td></tr>
</table>
<p style="color:#555;font-size:12px;">Generated by memecoin-intel. Not financial advice.</p>
</body></html>
"""
    body_plain = (
        f"Buy Now Signal Detected\n"
        f"Token:  {token}\n"
        f"Price:  ${price}\n"
        f"Score:  {score}/10\n"
        f"Reason: {reason}\n"
        f"Time:   {timestamp}\n"
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = GMAIL_USER
    msg["To"]      = ALERT_EMAIL
    msg.attach(MIMEText(body_plain, "plain"))
    msg.attach(MIMEText(body_html,  "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASS)
            server.sendmail(GMAIL_USER, ALERT_EMAIL, msg.as_string())
        log(f"Email sent for {token}")
        return True
    except Exception as e:
        log(f"Email error for {token}: {e}")
        return False


# ---------------------------------------------------------------------------
# Notion REST API
# ---------------------------------------------------------------------------
def log_to_notion(token: str, price: float, score: float, reason: str, timestamp: str, email_sent: bool) -> bool:
    if not NOTION_TOKEN:
        log("WARNING: NOTION_TOKEN not set — skipping Notion log")
        return False

    url = "https://api.notion.com/v1/pages"
    headers = {
        "Authorization":  f"Bearer {NOTION_TOKEN}",
        "Content-Type":   "application/json",
        "Notion-Version": "2022-06-28",
    }

    # Parse ISO timestamp → Notion date string (YYYY-MM-DDTHH:MM:SS+00:00)
    try:
        dt = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
        notion_ts = dt.strftime("%Y-%m-%dT%H:%M:%S+00:00")
    except Exception:
        notion_ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")

    payload = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": {
            "Signal":     {"title": [{"text": {"content": "buy now"}}]},
            "Token":      {"rich_text": [{"text": {"content": token}}]},
            "Price":      {"number": float(price) if price else None},
            "Score":      {"number": float(score)},
            "Reason":     {"rich_text": [{"text": {"content": reason}}]},
            "Timestamp":  {"date": {"start": notion_ts}},
            "Email Sent": {"checkbox": email_sent},
        },
    }
    # Remove null Price to avoid API error
    if payload["properties"]["Price"]["number"] is None:
        del payload["properties"]["Price"]

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=10)
        resp.raise_for_status()
        log(f"Notion row created for {token}")
        return True
    except Exception as e:
        log(f"Notion error for {token}: {e}")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    log("=== Signal check started ===")

    # Import and run the signal checker
    sys.path.insert(0, str(Path(__file__).parent))
    from signals import check_signals

    all_signals = check_signals()
    buy_now = [s for s in all_signals if s["signal"] == "buy now"]

    log(f"Evaluated {len(all_signals)} tokens — {len(buy_now)} buy now signal(s)")

    if not buy_now:
        log("No buy now signals this run.")
        return

    for sig in buy_now:
        token     = sig["token"]
        price     = sig.get("price", 0)
        score     = sig.get("score", 0)
        reason    = sig.get("reason", "")
        timestamp = sig.get("timestamp", datetime.now(timezone.utc).isoformat())

        log(f"BUY NOW → {token}  score={score}  price={price}")

        email_sent = send_email(token, price, score, reason, timestamp)
        log_to_notion(token, price, score, reason, timestamp, email_sent)

    log(f"=== Run complete: {len(buy_now)} alert(s) sent ===\n")


if __name__ == "__main__":
    main()
