"""Daily memecoin signal scanner.

Run directly or via GitHub Actions (.github/workflows/daily.yml).
Required env vars:
  GMAIL_USER            sender Gmail address
  GMAIL_APP_PASSWORD    Gmail app password (not your login password)
  NOTION_TOKEN          Notion integration secret
  NOTION_DATABASE_ID    target Notion database (defaults to the existing one)
"""

import os
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

from config import (
    EMAIL_RECIPIENT,
    GMAIL_APP_PASSWORD,
    GMAIL_USER,
    NOTION_DATABASE_ID,
    NOTION_TOKEN,
)
from signals import Signal, get_signals


# ── Notion ────────────────────────────────────────────────────────────────────

def _log_to_notion(sig: Signal) -> None:
    if not NOTION_TOKEN:
        print("NOTION_TOKEN not set — skipping Notion log.")
        return

    resp = requests.post(
        "https://api.notion.com/v1/pages",
        headers={
            "Authorization": f"Bearer {NOTION_TOKEN}",
            "Notion-Version": "2022-06-28",
            "Content-Type": "application/json",
        },
        json={
            "parent": {"database_id": NOTION_DATABASE_ID},
            "properties": {
                "Signal": {
                    "title": [{"text": {"content": f"{sig.coin} — Buy Now"}}]
                },
                "Coin": {
                    "rich_text": [{"text": {"content": sig.coin}}]
                },
                "Signal Type": {"select": {"name": "buy now"}},
                "Confidence": {"number": sig.confidence},
                "Price USD": {"number": sig.price_usd},
                "Reason": {
                    "rich_text": [{"text": {"content": sig.reason}}]
                },
                "Timestamp": {"date": {"start": sig.timestamp}},
            },
        },
        timeout=15,
    )
    if resp.ok:
        print(f"  Notion: logged {sig.coin}")
    else:
        print(f"  Notion error for {sig.coin}: {resp.status_code} {resp.text[:200]}")


# ── Email ─────────────────────────────────────────────────────────────────────

def _build_email_html(buy_signals: list[Signal], run_ts: str) -> str:
    rows = "".join(
        f"""
        <tr>
          <td style="padding:6px 12px;font-weight:bold">{s.coin}</td>
          <td style="padding:6px 12px;color:#16a34a;font-weight:bold">BUY NOW</td>
          <td style="padding:6px 12px">${s.price_usd:.8g}</td>
          <td style="padding:6px 12px;color:#16a34a">+{s.price_change_24h:.1f}%</td>
          <td style="padding:6px 12px">{int(s.confidence * 100)}%</td>
          <td style="padding:6px 12px;color:#6b7280">{s.reason}</td>
        </tr>"""
        for s in buy_signals
    )
    return f"""
    <html><body style="font-family:sans-serif;background:#f9fafb;padding:24px">
      <h2 style="color:#111827">Memecoin Buy Now Signals</h2>
      <p style="color:#6b7280">{run_ts}</p>
      <table border="1" cellpadding="0" cellspacing="0"
             style="border-collapse:collapse;background:white;border-color:#e5e7eb">
        <thead style="background:#111827;color:white">
          <tr>
            <th style="padding:8px 12px">Coin</th>
            <th style="padding:8px 12px">Signal</th>
            <th style="padding:8px 12px">Price USD</th>
            <th style="padding:8px 12px">24h</th>
            <th style="padding:8px 12px">Confidence</th>
            <th style="padding:8px 12px">Reason</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="margin-top:24px;color:#9ca3af;font-size:12px">
        Generated by memecoin-intel &middot; {run_ts}
      </p>
    </body></html>
    """


def _send_email(buy_signals: list[Signal], run_ts: str) -> None:
    if not GMAIL_USER or not GMAIL_APP_PASSWORD:
        print("GMAIL_USER / GMAIL_APP_PASSWORD not set — skipping email.")
        return

    subject = (
        f"🚀 {len(buy_signals)} Buy Now signal(s) — "
        f"{datetime.now().strftime('%Y-%m-%d')}"
    )
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_USER
    msg["To"] = EMAIL_RECIPIENT
    msg.attach(MIMEText(_build_email_html(buy_signals, run_ts), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        smtp.sendmail(GMAIL_USER, EMAIL_RECIPIENT, msg.as_string())

    print(f"Email sent → {EMAIL_RECIPIENT} ({len(buy_signals)} signal(s))")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    run_ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    print(f"[{run_ts}] memecoin-intel daily scan starting...")

    all_signals = get_signals()
    buy_signals = [s for s in all_signals if s.signal == "buy now"]

    print(f"Signals: {len(all_signals)} total, {len(buy_signals)} buy now.")

    for sig in buy_signals:
        print(
            f"  BUY NOW  {sig.coin:10s}  "
            f"${sig.price_usd:.8g}  "
            f"conf={sig.confidence:.0%}  "
            f"{sig.reason}"
        )
        _log_to_notion(sig)

    if buy_signals:
        _send_email(buy_signals, run_ts)
    else:
        print("No buy now signals today — no email sent.")

    print("Done.")


if __name__ == "__main__":
    main()
