"""
Daily runner: checks memecoin signals, logs 'buy now' hits to Notion,
and sends an email digest to the configured recipient.

Environment variables required (see .env.example):
  NOTION_TOKEN          - Notion integration token
  NOTION_DATABASE_ID    - Target Notion database ID
  GMAIL_SENDER          - Gmail address used to send alerts
  GMAIL_APP_PASSWORD    - Gmail App Password (not account password)
  ALERT_EMAIL           - Recipient email address
"""
import os
import json
import smtplib
import logging
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

from signals import get_buy_signals

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
)
log = logging.getLogger(__name__)

NOTION_API_URL = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"

NOTION_TOKEN = os.environ.get("NOTION_TOKEN", "")
NOTION_DATABASE_ID = os.environ.get(
    "NOTION_DATABASE_ID", "347d4906-1af0-4a12-b116-e0601217bcaf"
)
GMAIL_SENDER = os.environ.get("GMAIL_SENDER", "")
GMAIL_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD", "")
ALERT_EMAIL = os.environ.get("ALERT_EMAIL", "vickomela36@gmail.com")


# ── Notion ────────────────────────────────────────────────────────────────────

def _notion_headers() -> dict:
    return {
        "Authorization": f"Bearer {NOTION_TOKEN}",
        "Content-Type": "application/json",
        "Notion-Version": NOTION_VERSION,
    }


def log_signal_to_notion(signal: dict, email_sent: bool = False) -> bool:
    """Create a row in the Notion database for this signal."""
    payload = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": {
            "Token Name": {
                "title": [{"text": {"content": signal["token_name"]}}]
            },
            "Symbol": {
                "rich_text": [{"text": {"content": signal["symbol"]}}]
            },
            "Signal": {"select": {"name": "buy now"}},
            "Price USD": {
                "rich_text": [{"text": {"content": signal["price_usd"]}}]
            },
            "24h Change %": {
                # Notion 'percent' format stores decimals: 15% → 0.15
                "number": round(signal["price_change_24h_pct"] / 100, 6)
            },
            "Volume 24h USD": {"number": signal["volume_24h_usd"]},
            "Liquidity USD": {"number": signal["liquidity_usd"]},
            "Vol/Liq Ratio": {"number": signal["vol_liq_ratio"]},
            "Pair Address": {
                "rich_text": [{"text": {"content": signal["pair_address"]}}]
            },
            "DexScreener URL": {"url": signal["dexscreener_url"] or None},
            "Timestamp": {"date": {"start": signal["timestamp"]}},
            "Email Sent": {"checkbox": email_sent},
        },
    }
    try:
        resp = requests.post(
            f"{NOTION_API_URL}/pages",
            headers=_notion_headers(),
            json=payload,
            timeout=15,
        )
        resp.raise_for_status()
        log.info("Logged to Notion: %s (%s)", signal["token_name"], signal["symbol"])
        return True
    except Exception as exc:
        log.error("Notion log failed for %s: %s", signal["token_name"], exc)
        return False


# ── Gmail ─────────────────────────────────────────────────────────────────────

def _build_email_html(signals: list[dict]) -> str:
    rows = ""
    for s in signals:
        rows += f"""
        <tr>
          <td><b>{s['token_name']}</b> ({s['symbol']})</td>
          <td>{s['chain'].upper()}</td>
          <td>${s['price_usd']}</td>
          <td style="color:green">+{s['price_change_24h_pct']:.1f}%</td>
          <td>${s['volume_24h_usd']:,.0f}</td>
          <td>${s['liquidity_usd']:,.0f}</td>
          <td>{s['vol_liq_ratio']:.2f}x</td>
          <td><a href="{s['dexscreener_url']}">View</a></td>
        </tr>"""

    return f"""
    <html><body style="font-family:sans-serif">
    <h2>🚀 Memecoin Buy Now Signals – {datetime.now(timezone.utc).strftime('%Y-%m-%d UTC')}</h2>
    <p>{len(signals)} token(s) triggered a <b>buy now</b> signal today.</p>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse">
      <tr style="background:#f0f0f0">
        <th>Token</th><th>Chain</th><th>Price</th>
        <th>24h Chg</th><th>Vol 24h</th><th>Liquidity</th>
        <th>Vol/Liq</th><th>Link</th>
      </tr>
      {rows}
    </table>
    <p style="color:gray;font-size:12px">
      Generated by memecoin-intel · Data via DexScreener
    </p>
    </body></html>"""


def send_email_alert(signals: list[dict]) -> bool:
    """Send a Gmail alert with the buy now signal digest."""
    if not GMAIL_SENDER or not GMAIL_APP_PASSWORD:
        log.warning("Gmail credentials not set; skipping email.")
        return False

    subject = (
        f"[Memecoin Intel] {len(signals)} Buy Now Signal(s) – "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_SENDER
    msg["To"] = ALERT_EMAIL

    plain = "\n".join(
        f"• {s['token_name']} ({s['symbol']}) on {s['chain'].upper()} "
        f"| ${s['price_usd']} | +{s['price_change_24h_pct']:.1f}% | {s['dexscreener_url']}"
        for s in signals
    )
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(_build_email_html(signals), "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(GMAIL_SENDER, GMAIL_APP_PASSWORD)
            smtp.sendmail(GMAIL_SENDER, ALERT_EMAIL, msg.as_string())
        log.info("Email sent to %s with %d signal(s)", ALERT_EMAIL, len(signals))
        return True
    except Exception as exc:
        log.error("Email send failed: %s", exc)
        return False


# ── Main ──────────────────────────────────────────────────────────────────────

def run():
    log.info("Starting daily signal check – %s", datetime.now(timezone.utc).isoformat())

    signals = get_buy_signals()
    log.info("Signal scan complete: %d buy now signal(s) found", len(signals))

    if not signals:
        log.info("No buy now signals today. Nothing to send or log.")
        return

    email_sent = send_email_alert(signals)

    for signal in signals:
        log.info("Processing: %s (%s)", signal["token_name"], signal["symbol"])
        log_signal_to_notion(signal, email_sent=email_sent)

    print(json.dumps({"date": datetime.now(timezone.utc).date().isoformat(),
                       "signals_found": len(signals),
                       "email_sent": email_sent}))


if __name__ == "__main__":
    run()
