"""Daily automation: check buy-now signals, send email alert, log to Notion."""

import smtplib
import sys
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

import config
from signals import get_buy_now_signals


# ── Notion ────────────────────────────────────────────────────────────────────

def _notion_headers() -> dict:
    return {
        "Authorization": f"Bearer {config.NOTION_TOKEN}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28",
    }


def log_to_notion(signal: dict) -> None:
    detected = signal["detected_at"][:10]  # YYYY-MM-DD

    payload = {
        "parent": {"database_id": config.NOTION_DATABASE_ID},
        "properties": {
            "Coin": {
                "title": [{"text": {"content": f"{signal['coin']} ({signal['symbol']})"}}]
            },
            "Signal": {"select": {"name": signal["signal"]}},
            "Price USD": {"number": signal["price_usd"]},
            "Price Change 24h %": {"number": round(signal["price_change_24h"], 2)},
            "Market Cap USD": {"number": signal["market_cap_usd"]},
            "Volume 24h USD": {"number": signal["volume_24h_usd"]},
            "Detected At": {"date": {"start": detected}},
            "Source": {
                "rich_text": [{"text": {"content": signal["source"]}}]
            },
        },
    }

    resp = requests.post(
        "https://api.notion.com/v1/pages",
        json=payload,
        headers=_notion_headers(),
        timeout=15,
    )
    resp.raise_for_status()
    print(f"  [Notion] Logged: {signal['coin']} ({signal['signal']})")


# ── Email ─────────────────────────────────────────────────────────────────────

def _build_email_body(signals: list[dict]) -> tuple[str, str]:
    today = date.today().strftime("%B %d, %Y")
    rows_html = ""
    rows_text = ""

    for s in signals:
        rows_html += (
            f"<tr>"
            f"<td><b>{s['coin']}</b> ({s['symbol']})</td>"
            f"<td>${s['price_usd']:,.6f}</td>"
            f"<td>+{s['price_change_24h']:.1f}%</td>"
            f"<td>${s['market_cap_usd']:,.0f}</td>"
            f"<td>${s['volume_24h_usd']:,.0f}</td>"
            f"<td>{s['source']}</td>"
            f"</tr>"
        )
        rows_text += (
            f"  • {s['coin']} ({s['symbol']})\n"
            f"    Price: ${s['price_usd']:,.6f}  |  24h: +{s['price_change_24h']:.1f}%\n"
            f"    MCap: ${s['market_cap_usd']:,.0f}  |  Vol: ${s['volume_24h_usd']:,.0f}\n\n"
        )

    html = f"""
<html><body>
<h2>🚀 Memecoin BUY NOW Signals — {today}</h2>
<p>{len(signals)} signal(s) detected:</p>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:monospace">
  <tr style="background:#d4f7d4">
    <th>Coin</th><th>Price</th><th>24h Change</th>
    <th>Market Cap</th><th>Volume 24h</th><th>Source</th>
  </tr>
  {rows_html}
</table>
<p style="color:gray;font-size:11px">Generated by memecoin-intel · data from CoinGecko</p>
</body></html>"""

    text = f"Memecoin BUY NOW Signals — {today}\n{'='*50}\n\n{rows_text}"
    return html, text


def send_email(signals: list[dict]) -> None:
    html_body, text_body = _build_email_body(signals)
    today = date.today().strftime("%Y-%m-%d")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🚀 Buy Now Signal — {len(signals)} Memecoin(s) [{today}]"
    msg["From"]    = config.GMAIL_USER
    msg["To"]      = config.ALERT_RECIPIENT

    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(config.GMAIL_USER, config.GMAIL_APP_PASSWORD)
        server.sendmail(config.GMAIL_USER, config.ALERT_RECIPIENT, msg.as_string())

    print(f"  [Email] Sent to {config.ALERT_RECIPIENT}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print(f"[daily_runner] Fetching signals…")
    buy_signals = get_buy_now_signals(
        min_price_change=config.BUY_MIN_PRICE_CHANGE_24H,
        min_vol_to_mcap=config.BUY_MIN_VOLUME_TO_MCAP,
        min_market_cap=config.BUY_MIN_MARKET_CAP,
    )

    if not buy_signals:
        print("[daily_runner] No BUY NOW signals today — nothing to send.")
        sys.exit(0)

    print(f"[daily_runner] {len(buy_signals)} BUY NOW signal(s) found.")

    errors = []
    for signal in buy_signals:
        try:
            log_to_notion(signal)
        except Exception as exc:
            errors.append(f"Notion error for {signal['coin']}: {exc}")

    try:
        send_email(buy_signals)
    except Exception as exc:
        errors.append(f"Email error: {exc}")

    if errors:
        for e in errors:
            print(f"  [ERROR] {e}", file=sys.stderr)
        sys.exit(1)

    print("[daily_runner] Done.")


if __name__ == "__main__":
    main()
