"""
Hourly memecoin signal monitor.
- Fetches buy/sell/hold signals via signals.py
- Sends an email alert to ALERT_EMAIL for every 'buy now' signal
- Logs every 'buy now' signal to the Notion database

Run directly:  python3 monitor.py
Cron (hourly): 0 * * * * cd /path/to/memecoin-intel && python3 monitor.py >> cron.log 2>&1
"""

import logging
import os
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dotenv import load_dotenv
from notion_client import Client as NotionClient

from signals import SignalResult, get_signals

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.FileHandler("monitor.log"),
        logging.StreamHandler(),
    ],
)
log = logging.getLogger(__name__)

NOTION_DATABASE_ID = os.environ["NOTION_DATABASE_ID"]
ALERT_EMAIL = os.environ.get("ALERT_EMAIL", "vickomela36@gmail.com")
GMAIL_USER = os.environ["GMAIL_USER"]
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"]
NOTION_API_KEY = os.environ["NOTION_API_KEY"]


# ── email ────────────────────────────────────────────────────────────────────


def _build_html(signals: list[SignalResult]) -> str:
    rows = "".join(
        f"<tr>"
        f"<td><b>{s.token}</b></td>"
        f"<td>${s.price_usd:.8g}</td>"
        f"<td style='color:green'>{s.change_24h:+.2f}%</td>"
        f"<td>${s.volume_24h:,.0f}</td>"
        f"<td>{s.chain.upper()}</td>"
        f"<td>{s.notes}</td>"
        f"</tr>"
        for s in signals
    )
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"""
<html><body>
<h2>Memecoin Buy Now Signals &mdash; {timestamp}</h2>
<table border="1" cellpadding="6" style="border-collapse:collapse;font-family:monospace">
  <tr style="background:#e8f5e9">
    <th>Token</th><th>Price</th><th>24h Change</th>
    <th>Volume 24h</th><th>Chain</th><th>Notes</th>
  </tr>
  {rows}
</table>
<p style="color:#888;font-size:12px">Generated by memecoin-intel monitor</p>
</body></html>
"""


def send_email(buy_signals: list[SignalResult]) -> bool:
    tokens = ", ".join(s.token for s in buy_signals)
    subject = f"[Memecoin Intel] BUY NOW: {tokens}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_USER
    msg["To"] = ALERT_EMAIL
    msg.attach(MIMEText(_build_html(buy_signals), "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_USER, ALERT_EMAIL, msg.as_string())
        log.info("Email sent to %s — tokens: %s", ALERT_EMAIL, tokens)
        return True
    except Exception as exc:
        log.error("Email failed: %s", exc)
        return False


# ── notion ───────────────────────────────────────────────────────────────────


def log_to_notion(signal: SignalResult, email_sent: bool) -> None:
    notion = NotionClient(auth=NOTION_API_KEY)
    props: dict = {
        "Token": {"title": [{"text": {"content": signal.token}}]},
        "Signal": {"select": {"name": signal.signal}},
        "Price USD": {"number": signal.price_usd},
        "Volume 24h": {"number": signal.volume_24h},
        "24h Change %": {"number": signal.change_24h},
        "Email Sent": {"checkbox": email_sent},
        "Notes": {"rich_text": [{"text": {"content": signal.notes}}]},
    }
    if signal.market_cap is not None:
        props["Market Cap"] = {"number": signal.market_cap}

    try:
        notion.pages.create(
            parent={"database_id": NOTION_DATABASE_ID},
            properties=props,
        )
        log.info("Logged to Notion: %s (%s)", signal.token, signal.signal)
    except Exception as exc:
        log.error("Notion log failed for %s: %s", signal.token, exc)


# ── main ─────────────────────────────────────────────────────────────────────


def run() -> None:
    log.info("=== Signal check started ===")
    all_signals = get_signals()

    summary = [(s.token, s.signal) for s in all_signals]
    log.info("Results: %s", summary)

    buy_now = [s for s in all_signals if s.signal == "buy now"]
    if not buy_now:
        log.info("No 'buy now' signals this round.")
        return

    log.info("Buy now signals: %s", [s.token for s in buy_now])
    email_sent = send_email(buy_now)

    for signal in buy_now:
        log_to_notion(signal, email_sent)

    log.info("=== Done — %d buy now signal(s) processed ===", len(buy_now))


if __name__ == "__main__":
    run()
