"""Send email alerts via Gmail SMTP and log signals to Notion."""

import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from notion_client import Client

from config import ALERT_EMAIL, NOTION_DATABASE_ID
from signals import TokenSignal


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------

def _build_html(signals: list[TokenSignal], run_date: str) -> str:
    rows = "\n".join(
        f"<tr>"
        f"<td><b>{s.coin_symbol}</b></td>"
        f"<td>{s.chain}</td>"
        f"<td>{s.dex}</td>"
        f"<td>${s.price_usd:.8g}</td>"
        f"<td style='color:green'>+{s.price_change_24h:.1f}%</td>"
        f"<td>${s.volume_24h_usd:,.0f}</td>"
        f"<td>${s.liquidity_usd:,.0f}</td>"
        f"<td>{s.notes}</td>"
        f"</tr>"
        for s in signals
    )
    return f"""
<html><body>
<h2 style="font-family:sans-serif">🚀 Memecoin Buy Now Signals — {run_date}</h2>
<p style="font-family:sans-serif">{len(signals)} token(s) triggered the <b>Buy Now</b> signal today.</p>
<table border="1" cellpadding="8" cellspacing="0"
       style="border-collapse:collapse;font-family:monospace;font-size:13px">
  <tr style="background:#f0f0f0">
    <th>Symbol</th><th>Chain</th><th>DEX</th>
    <th>Price USD</th><th>24h Δ</th>
    <th>Volume 24h</th><th>Liquidity</th><th>Notes</th>
  </tr>
  {rows}
</table>
<p style="font-family:sans-serif;color:#888;font-size:11px">
  Source: DexScreener — generated by memecoin-intel
</p>
</body></html>
"""


def send_email(signals: list[TokenSignal]) -> None:
    gmail_user = os.environ["GMAIL_USER"]
    gmail_password = os.environ["GMAIL_APP_PASSWORD"]
    run_date = date.today().isoformat()

    msg = MIMEMultipart("alternative")
    msg["Subject"] = (
        f"[Memecoin Intel] {len(signals)} Buy Now Signal(s) — {run_date}"
    )
    msg["From"] = gmail_user
    msg["To"] = ALERT_EMAIL
    msg.attach(MIMEText(_build_html(signals, run_date), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_user, gmail_password)
        server.sendmail(gmail_user, ALERT_EMAIL, msg.as_string())

    print(f"[email] Sent {len(signals)} signal(s) to {ALERT_EMAIL}")


# ---------------------------------------------------------------------------
# Notion
# ---------------------------------------------------------------------------

def log_to_notion(signals: list[TokenSignal]) -> None:
    notion = Client(auth=os.environ["NOTION_API_KEY"])
    today = date.today().isoformat()

    for s in signals:
        notion.pages.create(
            parent={"database_id": NOTION_DATABASE_ID},
            properties={
                "Signal Name": {
                    "title": [{"text": {"content": s.signal_name}}]
                },
                "Coin Symbol": {
                    "rich_text": [{"text": {"content": s.coin_symbol}}]
                },
                "Chain": {
                    "rich_text": [{"text": {"content": s.chain}}]
                },
                "DEX": {
                    "rich_text": [{"text": {"content": s.dex}}]
                },
                "Pair Address": {
                    "rich_text": [{"text": {"content": s.pair_address}}]
                },
                "Price USD": {"number": s.price_usd},
                "Price Change 24h %": {"number": s.price_change_24h},
                "Volume 24h USD": {"number": s.volume_24h_usd},
                "Liquidity USD": {"number": s.liquidity_usd},
                "Signal": {"select": {"name": s.signal}},
                "Date": {"date": {"start": today}},
                "Email Sent": {"checkbox": True},
                "Notes": {
                    "rich_text": [{"text": {"content": s.notes}}]
                },
            },
        )
        print(f"[notion] Logged: {s.signal_name}")
