"""
Handles email alerts (Gmail SMTP) and Notion logging for buy-now signals.
"""

import smtplib
import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

from config import (
    ALERT_TO_EMAIL,
    ALERT_FROM_EMAIL,
    GMAIL_APP_PASSWORD,
    NOTION_TOKEN,
    NOTION_DATABASE_ID,
)


# ── Email ─────────────────────────────────────────────────────────────────────

def _build_email_html(signals) -> str:
    rows = ""
    for s in signals:
        rows += (
            f"<tr>"
            f"<td><b>{s.name} ({s.symbol})</b></td>"
            f"<td>${s.price_usd:,.6f}</td>"
            f"<td>{s.price_change_24h:+.2f}%</td>"
            f"<td>{s.score}/100</td>"
            f"<td>{', '.join(s.notes)}</td>"
            f"</tr>"
        )
    return f"""
    <html><body>
    <h2 style="color:#16a34a;">🚀 Memecoin BUY NOW Signals</h2>
    <p>The following coins triggered a <strong>buy now</strong> signal on {datetime.date.today()}:</p>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:monospace;">
      <thead style="background:#f0fdf4;">
        <tr>
          <th>Coin</th><th>Price (USD)</th><th>24h Change</th>
          <th>Score</th><th>Reasons</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
    <p style="color:#6b7280;font-size:12px;">
      Generated by memecoin-intel · {datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
    </p>
    </body></html>
    """


def send_email_alert(signals) -> bool:
    """Send a Gmail alert for buy-now signals. Returns True on success."""
    if not ALERT_FROM_EMAIL or not GMAIL_APP_PASSWORD:
        print("[notifier] Gmail credentials not set — skipping email.")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[memecoin-intel] BUY NOW signal — {datetime.date.today()}"
    msg["From"] = ALERT_FROM_EMAIL
    msg["To"] = ALERT_TO_EMAIL

    names = ", ".join(f"{s.name} ({s.symbol})" for s in signals)
    plain = (
        f"BUY NOW signals detected: {names}\n\n"
        + "\n".join(
            f"{s.name}: ${s.price_usd:.6f}  score={s.score}  {s.price_change_24h:+.2f}% 24h"
            for s in signals
        )
    )
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(_build_email_html(signals), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(ALERT_FROM_EMAIL, GMAIL_APP_PASSWORD)
        smtp.sendmail(ALERT_FROM_EMAIL, ALERT_TO_EMAIL, msg.as_string())

    print(f"[notifier] Email sent to {ALERT_TO_EMAIL}")
    return True


# ── Notion ────────────────────────────────────────────────────────────────────

_NOTION_API = "https://api.notion.com/v1"
_NOTION_VERSION = "2022-06-28"


def _notion_headers() -> dict:
    return {
        "Authorization": f"Bearer {NOTION_TOKEN}",
        "Notion-Version": _NOTION_VERSION,
        "Content-Type": "application/json",
    }


def log_signal_to_notion(signal, email_sent: bool = False) -> str | None:
    """Create a row in the Notion 'Memecoin Buy Now Signals' database."""
    if not NOTION_TOKEN:
        print("[notifier] NOTION_TOKEN not set — skipping Notion log.")
        return None

    now = datetime.datetime.utcnow().isoformat()
    payload = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": {
            "Signal": {
                "title": [{"text": {"content": f"{signal.name} — {signal.signal.upper()}"}}]
            },
            "Coin": {
                "rich_text": [{"text": {"content": f"{signal.name} ({signal.symbol})"}}]
            },
            "Price": {"number": signal.price_usd},
            "Signal Score": {"number": signal.score},
            "Timestamp": {"date": {"start": now}},
            "Status": {"select": {"name": signal.signal}},
            "Email Sent": {"checkbox": email_sent},
            "Notes": {
                "rich_text": [{"text": {"content": "; ".join(signal.notes)}}]
            },
        },
    }

    resp = requests.post(
        f"{_NOTION_API}/pages",
        headers=_notion_headers(),
        json=payload,
        timeout=15,
    )
    if resp.ok:
        page_id = resp.json().get("id")
        print(f"[notifier] Notion row created for {signal.name} (id={page_id})")
        return page_id
    else:
        print(f"[notifier] Notion error {resp.status_code}: {resp.text}")
        return None
