"""Send Gmail alerts and log buy-now signals to the Notion database."""

import smtplib
import requests
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import config
from signals import Signal


# ── Email ──────────────────────────────────────────────────────────────────────

def _build_email_html(signals: list[Signal]) -> str:
    rows = ""
    for s in signals:
        change_color = "green" if s.price_change_24h > 0 else "red"
        strength_colors = {"Strong": "#16a34a", "Moderate": "#ca8a04", "Weak": "#ea580c"}
        sc = strength_colors.get(s.signal_strength, "#6b7280")
        rows += f"""
        <tr>
          <td><b>{s.token}</b></td>
          <td>{s.chain.upper()}</td>
          <td>${s.price_usd:.8g}</td>
          <td style="color:{change_color}"><b>+{s.price_change_24h:.1f}%</b></td>
          <td>${s.volume_24h:,.0f}</td>
          <td>${s.liquidity_usd:,.0f}</td>
          <td style="color:{sc}"><b>{s.signal_strength}</b></td>
          <td style="color:#6b7280;font-size:12px">{s.notes or "—"}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;background:#f9fafb;padding:24px">
  <div style="max-width:900px;background:white;border-radius:12px;padding:24px;
              box-shadow:0 1px 4px rgba(0,0,0,.1)">
    <h2 style="color:#111827">🚀 Memecoin Buy Now Signals — {date.today().isoformat()}</h2>
    <p style="color:#374151">{len(signals)} signal(s) detected by the daily scanner.</p>
    <table border="0" cellpadding="8" cellspacing="0"
           style="width:100%;border-collapse:collapse;font-size:13px">
      <thead>
        <tr style="background:#f3f4f6;color:#374151">
          <th align="left">Token</th>
          <th align="left">Chain</th>
          <th align="left">Price</th>
          <th align="left">24h Δ</th>
          <th align="left">Volume 24h</th>
          <th align="left">Liquidity</th>
          <th align="left">Strength</th>
          <th align="left">Notes</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
    <p style="color:#9ca3af;font-size:11px;margin-top:20px">
      Data via DEXScreener. Not financial advice. Generated by memecoin-intel.
    </p>
  </div>
</body>
</html>"""


def send_email(signals: list[Signal]) -> None:
    if not signals:
        return

    subject = (
        f"🚀 {len(signals)} Memecoin Buy Signal{'s' if len(signals) > 1 else ''}"
        f" — {date.today().isoformat()}"
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.GMAIL_USER
    msg["To"] = config.NOTIFY_EMAIL

    plain = "\n".join(
        f"{s.token} ({s.chain}) +{s.price_change_24h:.1f}% | Vol ${s.volume_24h:,.0f}"
        f" | Liq ${s.liquidity_usd:,.0f} | {s.signal_strength}"
        for s in signals
    )
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(_build_email_html(signals), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(config.GMAIL_USER, config.GMAIL_APP_PASSWORD)
        server.sendmail(config.GMAIL_USER, config.NOTIFY_EMAIL, msg.as_string())

    print(f"Email sent → {config.NOTIFY_EMAIL}")


# ── Notion ──────────────────────────────────────────────────────────────────────

_NOTION_API = "https://api.notion.com/v1/pages"
_NOTION_VERSION = "2022-06-28"


def log_to_notion(signal: Signal, email_sent: bool = False) -> None:
    headers = {
        "Authorization": f"Bearer {config.NOTION_TOKEN}",
        "Content-Type": "application/json",
        "Notion-Version": _NOTION_VERSION,
    }
    payload = {
        "parent": {"database_id": config.NOTION_DATABASE_ID},
        "properties": {
            "Token": {
                "title": [{"text": {"content": signal.token}}]
            },
            "Signal Date": {
                "date": {"start": signal.timestamp.date().isoformat()}
            },
            "Token Address": {
                "rich_text": [{"text": {"content": signal.address}}]
            },
            "Chain": {
                "rich_text": [{"text": {"content": signal.chain}}]
            },
            "Price USD": {"number": signal.price_usd},
            "Price Change 24h %": {"number": signal.price_change_24h},
            "Volume 24h USD": {"number": signal.volume_24h},
            "Liquidity USD": {"number": signal.liquidity_usd},
            "Signal Strength": {"select": {"name": signal.signal_strength}},
            "Email Sent": {"checkbox": email_sent},
            "Notes": {
                "rich_text": [{"text": {"content": signal.notes or ""}}]
            },
        },
    }
    resp = requests.post(_NOTION_API, json=payload, headers=headers, timeout=15)
    resp.raise_for_status()
    print(f"Logged {signal.token} → Notion")
