"""
Email and Notion logging for buy signals.
"""

import smtplib
import json
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

from config import (
    ALERT_EMAIL,
    GMAIL_USER,
    GMAIL_APP_PASSWORD,
    NOTION_API_KEY,
    NOTION_DATABASE_ID,
)

NOTION_API_BASE = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"


def send_email(signals: list[dict]) -> None:
    """Send a 'buy now' alert email for the given signals."""
    if not GMAIL_USER or not GMAIL_APP_PASSWORD:
        print("[email] GMAIL_USER / GMAIL_APP_PASSWORD not set — skipping email.")
        return

    subject = f"[Memecoin Intel] Buy Signal Alert — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"

    rows = "\n".join(
        f"  • {s['token']}  |  ${s['price']:.6f}  |  +{s['price_change_24h']:.1f}% 24h  |  Vol ${s['volume_24h']:,.0f}"
        for s in signals
    )

    body = (
        f"Buy signal(s) detected on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}:\n\n"
        f"{rows}\n\n"
        "---\nThis alert was generated by memecoin-intel. Not financial advice."
    )

    html_body = (
        "<h2>Memecoin Buy Signal Alert</h2>"
        f"<p>Detected on <strong>{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</strong></p>"
        "<table border='1' cellpadding='6' cellspacing='0' style='border-collapse:collapse;font-family:monospace'>"
        "<tr><th>Token</th><th>Price (USD)</th><th>24h Change</th><th>Volume 24h</th></tr>"
        + "".join(
            f"<tr><td>{s['token']}</td><td>${s['price']:.6f}</td>"
            f"<td style='color:green'>+{s['price_change_24h']:.1f}%</td>"
            f"<td>${s['volume_24h']:,.0f}</td></tr>"
            for s in signals
        )
        + "</table>"
        "<p style='color:grey;font-size:12px'>Not financial advice.</p>"
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_USER
    msg["To"] = ALERT_EMAIL
    msg.attach(MIMEText(body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_USER, ALERT_EMAIL, msg.as_string())

    print(f"[email] Alert sent to {ALERT_EMAIL} for {len(signals)} signal(s).")


def log_to_notion(signal: dict) -> None:
    """Create a row in the Notion 'Memecoin Buy Signals' database."""
    if not NOTION_API_KEY:
        print("[notion] NOTION_API_KEY not set — skipping Notion log.")
        return

    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")

    payload = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": {
            "Token": {
                "title": [{"text": {"content": signal["token"]}}]
            },
            "Signal": {
                "select": {"name": signal["signal"]}
            },
            "Price": {
                "number": signal["price"]
            },
            "Market Cap": {
                "number": signal["market_cap"]
            },
            "Volume 24h": {
                "number": signal["volume_24h"]
            },
            "Timestamp": {
                "date": {"start": now_iso}
            },
            "Notes": {
                "rich_text": [
                    {"text": {"content": f"24h change: +{signal['price_change_24h']:.2f}%"}}
                ]
            },
            "Email Sent": {
                "checkbox": True
            },
        },
    }

    headers = {
        "Authorization": f"Bearer {NOTION_API_KEY}",
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
    }

    resp = requests.post(
        f"{NOTION_API_BASE}/pages",
        headers=headers,
        data=json.dumps(payload),
        timeout=15,
    )
    resp.raise_for_status()
    print(f"[notion] Logged '{signal['token']}' buy signal.")
