"""Daily runner: check signals → email vickomela36@gmail.com → log to Notion."""

import os
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

from signals import TokenSignal, get_signals

# ── Environment variables (set as GitHub Actions secrets) ─────────────────────
GMAIL_USER = os.environ["GMAIL_USER"]               # your Gmail address
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"]  # Gmail app password
NOTIFY_EMAIL = os.environ.get("NOTIFY_EMAIL", "vickomela36@gmail.com")

NOTION_API_KEY = os.environ["NOTION_API_KEY"]        # Notion integration token
NOTION_DATABASE_ID = "673a2e467e3f4db1ad85fb0c320854d3"

# ── Notion ─────────────────────────────────────────────────────────────────────
_NOTION_HEADERS = {
    "Authorization": f"Bearer {NOTION_API_KEY}",
    "Notion-Version": "2022-06-28",
    "Content-Type": "application/json",
}


def log_to_notion(signal: TokenSignal) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")

    props: dict = {
        "Coin": {"title": [{"text": {"content": f"{signal.name} ({signal.symbol})"}}]},
        "Signal": {"select": {"name": signal.signal}},
        "Price USD": {"number": signal.price_usd},
        "Volume 24h USD": {"number": signal.volume_24h},
        "Price Change 24h %": {"number": signal.price_change_24h},
        "Detected At": {"date": {"start": now}},
        "Source": {"rich_text": [{"text": {"content": signal.source[:2000]}}]},
    }

    if signal.market_cap:
        props["Market Cap USD"] = {"number": signal.market_cap}

    if signal.notes:
        props["Notes"] = {"rich_text": [{"text": {"content": signal.notes}}]}

    resp = requests.post(
        "https://api.notion.com/v1/pages",
        headers=_NOTION_HEADERS,
        json={"parent": {"database_id": NOTION_DATABASE_ID}, "properties": props},
        timeout=15,
    )

    if resp.ok:
        print(f"[notion] Logged: {signal.name} ({signal.symbol})")
    else:
        print(f"[notion] Error {resp.status_code} for {signal.name}: {resp.text[:300]}")


# ── Gmail ──────────────────────────────────────────────────────────────────────

def _build_html(signals: list[TokenSignal], date_str: str) -> str:
    rows = ""
    for s in signals:
        chart = f'<a href="{s.source}">chart ↗</a>' if s.source else "—"
        mc = f"${s.market_cap:,.0f}" if s.market_cap else "—"
        rows += (
            f"<tr>"
            f"<td><b>{s.name}</b> ({s.symbol})</td>"
            f"<td>${s.price_usd:.8f}</td>"
            f"<td>${s.volume_24h:,.0f}</td>"
            f"<td style='color:{'green' if s.price_change_24h >= 0 else 'red'}'>"
            f"{s.price_change_24h:+.1f}%</td>"
            f"<td>{mc}</td>"
            f"<td>{chart}</td>"
            f"</tr>"
        )

    return f"""<!DOCTYPE html><html><body style="font-family:Arial,sans-serif">
<h2 style="color:#0070f3">🚀 Memecoin BUY NOW Signals — {date_str}</h2>
<p><b>{len(signals)}</b> token(s) triggered buy criteria on Solana today.</p>
<table border="1" cellpadding="8" cellspacing="0"
       style="border-collapse:collapse;width:100%;font-size:13px">
  <thead style="background:#0070f3;color:white">
    <tr><th>Token</th><th>Price</th><th>Vol 24h</th>
        <th>Change 24h</th><th>Mkt Cap</th><th>Link</th></tr>
  </thead>
  <tbody>{rows}</tbody>
</table>
<p style="color:#888;font-size:11px;margin-top:20px">
  Generated by memecoin-intel · Data: DexScreener · Criteria: vol ≥$100k,
  price ≥+15%, liquidity ≥$50k, mkt cap ≤$50M
</p>
</body></html>"""


def send_buy_email(signals: list[TokenSignal]) -> None:
    date_str = datetime.now().strftime("%Y-%m-%d")
    subject = f"[Memecoin Intel] {len(signals)} BUY NOW signal(s) — {date_str}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_USER
    msg["To"] = NOTIFY_EMAIL

    plain = "\n".join(
        f"• {s.name} ({s.symbol}): ${s.price_usd} | vol ${s.volume_24h:,.0f}"
        f" | {s.price_change_24h:+.1f}% | {s.source}"
        for s in signals
    )
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(_build_html(signals, date_str), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_USER, NOTIFY_EMAIL, msg.as_string())

    print(f"[email] Sent to {NOTIFY_EMAIL} — {len(signals)} signal(s)")


# ── Main ───────────────────────────────────────────────────────────────────────

def run() -> None:
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Starting daily signal check…")

    all_signals = get_signals()
    buy_signals = [s for s in all_signals if s.signal == "buy now"]

    print(f"Scanned {len(all_signals)} Solana pairs → {len(buy_signals)} buy now signal(s)")

    for signal in buy_signals:
        log_to_notion(signal)

    if buy_signals:
        send_buy_email(buy_signals)
    else:
        print("No buy now signals today — no email sent.")

    print("Done.")


if __name__ == "__main__":
    run()
