#!/usr/bin/env python3
"""Daily memecoin signal runner — email + Notion logging."""

import smtplib
import sys
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

import config
from signals import get_signals

NOTION_API = "https://api.notion.com/v1/pages"
NOTION_HEADERS = {
    "Notion-Version": "2022-06-28",
    "Content-Type": "application/json",
}


# ── Email ────────────────────────────────────────────────────────────────────

def build_email_html(signals):
    rows = ""
    for s in signals:
        rows += (
            f"<tr>"
            f"<td><b>{s['name']} ({s['symbol']})</b></td>"
            f"<td>{s['chain'].upper()}</td>"
            f"<td>${s['price_usd']}</td>"
            f"<td>{s['price_change_1h']:+.1f}%</td>"
            f"<td>{s['price_change_24h']:+.1f}%</td>"
            f"<td>${s['volume_24h']:,.0f}</td>"
            f"<td>${s['liquidity_usd']:,.0f}</td>"
            f"<td><a href='{s['url']}'>DexScreener</a></td>"
            f"</tr>"
        )
    return f"""
<html><body>
<h2>🚨 Memecoin Buy Now Signals — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</h2>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:monospace">
  <tr style="background:#222;color:#fff">
    <th>Token</th><th>Chain</th><th>Price</th>
    <th>1h Δ</th><th>24h Δ</th><th>Vol 24h</th><th>Liquidity</th><th>Link</th>
  </tr>
  {rows}
</table>
<p style="color:gray;font-size:12px">Generated by memecoin-intel — do your own research before trading.</p>
</body></html>"""


def send_email(buy_now_signals):
    if not config.GMAIL_APP_PASSWORD:
        print("[email] GMAIL_APP_PASSWORD not set — skipping")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = (
        f"🚨 {len(buy_now_signals)} Memecoin Buy Now Signal(s) — "
        f"{datetime.utcnow().strftime('%Y-%m-%d')}"
    )
    msg["From"] = config.GMAIL_SENDER
    msg["To"] = config.RECIPIENT_EMAIL

    plain = "\n".join(
        f"{s['name']} ({s['symbol']}) | {s['chain']} | "
        f"1h: {s['price_change_1h']:+.1f}% | 24h: {s['price_change_24h']:+.1f}% | "
        f"Vol: ${s['volume_24h']:,.0f} | {s['url']}"
        for s in buy_now_signals
    )
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(build_email_html(buy_now_signals), "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as srv:
            srv.login(config.GMAIL_SENDER, config.GMAIL_APP_PASSWORD)
            srv.sendmail(config.GMAIL_SENDER, config.RECIPIENT_EMAIL, msg.as_string())
        print(f"[email] Sent to {config.RECIPIENT_EMAIL}")
        return True
    except Exception as exc:
        print(f"[email] Failed: {exc}")
        return False


# ── Notion ───────────────────────────────────────────────────────────────────

def log_to_notion(signal):
    if not config.NOTION_TOKEN:
        print("[notion] NOTION_TOKEN not set — skipping")
        return False

    chain = signal["chain"].lower()
    known_chains = {"solana", "ethereum", "bsc", "base", "polygon", "avalanche"}
    chain_value = chain if chain in known_chains else "other"

    try:
        price = float(signal["price_usd"])
    except (ValueError, TypeError):
        price = 0.0

    payload = {
        "parent": {"database_id": config.NOTION_DATABASE_ID},
        "properties": {
            "Token Name": {
                "title": [{"text": {"content": f"{signal['name']} ({signal['symbol']})"}}]
            },
            "Signal": {"select": {"name": "Buy Now"}},
            "Price USD": {"number": price},
            "1h Change %": {"number": signal["price_change_1h"]},
            "24h Change %": {"number": signal["price_change_24h"]},
            "Volume 24h": {"number": signal["volume_24h"]},
            "Liquidity USD": {"number": signal["liquidity_usd"]},
            "Chain": {"select": {"name": chain_value}},
            "Timestamp": {"date": {"start": signal["timestamp"]}},
            "DexScreener URL": {"url": signal["url"] or None},
            "Contract Address": {
                "rich_text": [{"text": {"content": signal["address"]}}]
            },
        },
    }

    headers = {**NOTION_HEADERS, "Authorization": f"Bearer {config.NOTION_TOKEN}"}
    try:
        resp = requests.post(NOTION_API, headers=headers, json=payload, timeout=10)
        resp.raise_for_status()
        print(f"[notion] Logged: {signal['name']} ({signal['symbol']})")
        return True
    except Exception as exc:
        print(f"[notion] Failed for {signal['symbol']}: {exc}")
        return False


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    print(f"\n{'='*60}")
    print(f"Memecoin signal scan — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"{'='*60}")

    signals = get_signals()
    buy_now = [s for s in signals if s["signal"] == "buy now"]

    print(f"\nScanned {len(signals)} tokens → {len(buy_now)} buy now signal(s)\n")
    for s in signals:
        tag = "★ BUY NOW" if s["signal"] == "buy now" else f"  {s['signal'].upper()}"
        print(
            f"  {tag:12s} {s['symbol']:10s} "
            f"1h:{s['price_change_1h']:+6.1f}% "
            f"24h:{s['price_change_24h']:+7.1f}% "
            f"vol:${s['volume_24h']:>12,.0f}  score:{s['score']}"
        )

    if buy_now:
        print(f"\n[→] Sending email alert …")
        send_email(buy_now)
        print(f"[→] Logging {len(buy_now)} signal(s) to Notion …")
        for s in buy_now:
            log_to_notion(s)
    else:
        print("\nNo buy now signals today.")

    print(f"\nDone.\n")
    return buy_now


if __name__ == "__main__":
    result = main()
    sys.exit(0)
